context("writeIATfull participant-facing options")

# correct.error and note change what the participant is told and how key presses are
# handled. Only the (TRUE, TRUE) combination was covered, so the on-screen note for a
# non-forced-correction IAT was never generated by any test.

instr_args <- function(...) {
  utils::modifyList(
    list(
      IATname = "instr",
      posname = "Pleasant", negname = "Unpleasant",
      Aname = "Flowers", Bname = "Insects",
      catType = "words",
      poswords = c("Gentle", "Enjoy", "Heaven", "Cheer", "Happy", "Love", "Friend"),
      negwords = c("Poison", "Evil", "Gloom", "Damage", "Vomit", "Ugly", "Hurt"),
      tgtType = "words",
      Awords = c("Orchid", "Tulip", "Rose", "Daffodil", "Daisy", "Lilac", "Lily"),
      Bwords = c("Wasp", "Flea", "Roach", "Centipede", "Moth", "Bedbug", "Gnat"),
      n = c(20, 20, 20, 40, 40, 20, 40),
      qsf = FALSE
    ),
    list(...)
  )
}

# All HTML and JavaScript generated for one permutation, as a single string.
instr_text <- function() {
  files <- list.files("1 instr_rp", pattern = "\\.txt$", full.names = TRUE)
  paste(unlist(lapply(files, readLines, warn = FALSE)), collapse = "\n")
}

build_instr <- function(...) {
  in_temp_dir({
    do.call(writeIATfull, instr_args(...))
    instr_text()
  })
}

# Both key handlers are defined in the template regardless of the settings; what
# changes is which one is registered as the keyup listener. Test the registration.
FORCED_HANDLER <- "keyup', keyCheckForcedError, false"
PLAIN_HANDLER <- "keyup', keyCheck, false"


test_that("forced error correction with a note tells participants how to correct", {
  txt <- build_instr(correct.error = TRUE, note = TRUE)

  expect_true(grepl("Correct mistakes by pressing the other key", txt, fixed = TRUE))
  expect_true(grepl(FORCED_HANDLER, txt, fixed = TRUE))
})

test_that("a note without forced error correction omits the correction sentence", {
  txt <- build_instr(correct.error = FALSE, note = TRUE)

  expect_true(grepl("Press E or I to advance to the next word/image.", txt, fixed = TRUE))
  expect_false(grepl("Correct mistakes by pressing the other key", txt, fixed = TRUE))
  # the non-forced variant registers the ordinary key handler
  expect_true(grepl(PLAIN_HANDLER, txt, fixed = TRUE))
  expect_false(grepl(FORCED_HANDLER, txt, fixed = TRUE))
})

test_that("no note leaves the on-screen note empty", {
  for (correct.error in c(TRUE, FALSE)) {
    txt <- build_instr(correct.error = correct.error, note = FALSE)

    expect_false(grepl("Press E or I to advance", txt, fixed = TRUE),
      info = paste("correct.error =", correct.error)
    )
    expect_true(grepl("note.innerHTML = \"\";", txt, fixed = TRUE),
      info = paste("correct.error =", correct.error)
    )
  }
})

test_that("forced error correction selects the forced-error key handler", {
  forced <- build_instr(correct.error = TRUE, note = FALSE)
  unforced <- build_instr(correct.error = FALSE, note = FALSE)

  expect_true(grepl(FORCED_HANDLER, forced, fixed = TRUE))
  expect_false(grepl(PLAIN_HANDLER, forced, fixed = TRUE))

  expect_true(grepl(PLAIN_HANDLER, unforced, fixed = TRUE))
  expect_false(grepl(FORCED_HANDLER, unforced, fixed = TRUE))
})


## --- timing options ---------------------------------------------------------

test_that("a custom inter-trial pause reaches the generated JavaScript", {
  txt <- build_instr(pause = 750)

  expect_true(grepl("750", txt, fixed = TRUE))
})

test_that("errorpause is forced to match pause under forced error correction", {
  # With forced correction there is no error-message delay to configure, so iatgen
  # overrides errorpause. Setting it to something distinctive should have no effect.
  txt <- build_instr(correct.error = TRUE, pause = 250, errorpause = 1234)

  expect_false(grepl("1234", txt, fixed = TRUE))
})

test_that("errorpause is honoured when errors are not corrected", {
  txt <- build_instr(correct.error = FALSE, pause = 250, errorpause = 1234)

  expect_true(grepl("1234", txt, fixed = TRUE))
})


## --- internal argument guards -----------------------------------------------

# writeIATstim() is internal and writeIATfull() validates most of these before calling
# it, so these guards are defensive. Testing them directly documents the contract for
# any future caller.

test_that("writeIATstim rejects misspecified arguments", {
  base <- list(
    n = 20, posside = "right", Aside = "right",
    catType = "words", nPos = 0, nNeg = 0,
    poswords = letters[1:4], negwords = LETTERS[1:4],
    tgtType = "words", nA = 0, nB = 0,
    Awords = paste0("a", 1:4), Bwords = paste0("b", 1:4),
    write.me = FALSE, out = "unused.txt"
  )
  call_stim <- function(...) {
    do.call(iatgen:::writeIATstim, utils::modifyList(base, list(...)))
  }

  expect_error(call_stim(type = "combined", n = 21), "must be even")
  expect_error(call_stim(type = "combined", n = 22), "divisible by four")
  expect_error(
    call_stim(type = "combined", combined.type = "sideways"),
    "Type must be"
  )
  expect_error(call_stim(type = "nonsense"), "type of block")
  expect_error(call_stim(type = "target", catType = "pictures"), "Category must be")
  expect_error(call_stim(type = "target", tgtType = "pictures"), "Targets must be")
})

test_that("writeIATblocks warns when the image counts contradict the URL list", {
  # writeIATfull() derives nA/nB/nPos/nNeg from the same vectors it concatenates into
  # `imgs`, so the two can never disagree by that route. The guard protects a caller
  # that supplies the counts itself, which is how it is reached here.
  imgs <- paste0("https://example.com/i", 1:14, ".jpg")

  in_temp_dir({
    expect_warning(
      iatgen:::writeIATblocks(
        startqid = 1, foldernum = 1,
        posname = "Pleasant", negname = "Unpleasant", Aname = "A", Bname = "B",
        posstart = "right", Astart = "right", IATname = "blk",
        n = c(20, 20, 20, 40, 40, 20, 40),
        catType = "words", poswords = letters[1:7], negwords = LETTERS[1:7],
        nPos = 0, nNeg = 0,
        tgtType = "images", nA = 99, nB = 99,
        Awords = NULL, Bwords = NULL,
        Aimgs = imgs[1:7], Bimgs = imgs[8:14],
        swap = "target", imgs = imgs
      ),
      "did not match the number of images"
    )
  })
})


## --- trial timing -----------------------------------------------------------

# The survey times each trial by subtracting two timestamps. Taken from the wall
# clock, that difference can come out negative when the machine corrects its time
# mid-trial, which cleanIAT() then has to discard. performance.now() is monotonic
# and cannot do this.

# The explanatory comment in the template names both clocks whichever is selected, so
# these assert on the body of the timestamp function rather than on any mention of it.
PERF_TIMER <- "function iatTimestamp() { return performance.now(); }"
DATE_TIMER <- "function iatTimestamp() { return new Date().getTime(); }"

test_that("trials are timed with performance.now() by default", {
  txt <- build_instr()

  expect_true(grepl(PERF_TIMER, txt, fixed = TRUE))
  expect_false(grepl(DATE_TIMER, txt, fixed = TRUE))
})

test_that("timing = 'performance' is the same as the default", {
  expect_equal(build_instr(timing = "performance"), build_instr())
})

test_that("timing = 'date' restores the wall-clock timer", {
  txt <- build_instr(timing = "date")

  expect_true(grepl(DATE_TIMER, txt, fixed = TRUE))
  expect_false(grepl(PERF_TIMER, txt, fixed = TRUE))
})

test_that("reaction times are rounded under both timers", {
  # performance.now() is fractional. An unrounded difference would put a "." in the
  # response string, which cleanIAT() reads as a corrupted record - so the rounding
  # is what makes the monotonic timer usable at all.
  for (timing in c("performance", "date")) {
    txt <- build_instr(timing = timing)
    expect_true(
      grepl(
        "currentStimulus.reactionTime = Math.round(currentStimulus.end - currentStimulus.start);",
        txt,
        fixed = TRUE
      ),
      info = timing
    )
    expect_false(grepl("= currentStimulus.end - currentStimulus.start;", txt, fixed = TRUE),
      info = timing
    )
  }
})

test_that("every timestamp comes from the one helper", {
  # Three sites take a timestamp; if any kept calling a clock directly, that trial
  # would be timed against a different origin and the difference would be meaningless.
  # Counted within a single block's JavaScript, since build_instr() returns all seven.
  for (timing in c("performance", "date")) {
    js <- in_temp_dir({
      do.call(writeIATfull, instr_args(timing = timing))
      paste(readLines(file.path("1 instr_rp", "Q1 JavaScript_1.txt"), warn = FALSE), collapse = "\n")
    })
    expect_equal(length(gregexpr("iatTimestamp()", js, fixed = TRUE)[[1]]), 4,
      info = paste(timing, "- one definition plus three call sites")
    )
    expect_false(grepl("new Date().getTime()", js, fixed = TRUE) && timing == "performance",
      info = timing
    )
  }
})

test_that("an invalid timing argument is rejected", {
  in_temp_dir({
    expect_error(
      do.call(writeIATfull, instr_args(timing = "wallclock")),
      "timing"
    )
  })
})
